#ifndef FLIGHT_H
#define FLIGHT_H

#define MOTOR_MAPPING_VALUE(x,i) ((x & (0xFUL<<(i*4)))>>(i*4))
#define MOTOR_GET_INDEX(v) (v & 0x7UL)
#define MOTOR_IS_REVERSE(v) (v & 0x8UL)

#define MOTOR_SET_REVERSE(i,r) (r==0?(i):(i|0x8U))
#define MOTOR_PUT_MAPPING_VALUE(v, p,i,r) (v | (MOTOR_SET_REVERSE(i,r)<<(p*4)))

enum flight_status {
    FLIGHT_STATUS_READY,
    FLIGHT_STATUS_ANGLE_RATE_MODE,
    FLIGHT_STATUS_ANGLE_MODE,
    FLIGHT_STATUS_CALIBRATION_ACCEL,
    FLIGHT_STATUS_CALIBRATION_ACCEL_UP,
    FLIGHT_STATUS_CALIBRATION_ACCEL_DOWN,
    FLIGHT_STATUS_CALIBRATION_ACCEL_FORWARD,
    FLIGHT_STATUS_CALIBRATION_ACCEL_BACKWARD,
    FLIGHT_STATUS_CALIBRATION_ACCEL_LEFT,
    FLIGHT_STATUS_CALIBRATION_ACCEL_RIGHT,
    FLIGHT_STATUS_CALIBRATION_GYRO,
    FLIGHT_STATUS_CALIBRATION_COMPASS,
    FLIGHT_STATUS_MOTOR_TEST
};

#endif // FLIGHT_H
