#ifndef FLIGHT_H
#define FLIGHT_H

enum flight_status {
    FLIGHT_STATUS_READY,
    FLIGHT_STATUS_ANGLE_RATE_MODE,
    FLIGHT_STATUS_ANGLE_MODE,
    FLIGHT_STATUS_CALIBRATION_ACCEL,
    FLIGHT_STATUS_CALIBRATION_ACCEL_UP,
    FLIGHT_STATUS_CALIBRATION_ACCEL_DOWN,
    FLIGHT_STATUS_CALIBRATION_ACCEL_FORWARD,
    FLIGHT_STATUS_CALIBRATION_ACCEL_BACKWARD,
    FLIGHT_STATUS_CALIBRATION_ACCEL_LEFT,
    FLIGHT_STATUS_CALIBRATION_ACCEL_RIGHT,
    FLIGHT_STATUS_CALIBRATION_GYRO,
    FLIGHT_STATUS_CALIBRATION_COMPASS,
    FLIGHT_STATUS_MOTOR_TEST
};

#endif // FLIGHT_H
